In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [13]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3  = np.random.randint(10, size = (3, 4, 5))

In [14]:
x1

array([9, 2, 8, 6, 6, 9])

In [17]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [18]:
print("dtype: ", x3.dtype)

dtype:  int32


In [19]:
print("itemsize: ", x3.itemsize, " bytes")
print("nbytes: ", x3.nbytes, " bytes")

itemsize:  4  bytes
nbytes:  240  bytes


In [20]:
x1

array([9, 2, 8, 6, 6, 9])

In [22]:
x1[4]

6

In [26]:
x2

array([[1, 6, 8, 8],
       [3, 2, 3, 6],
       [3, 6, 5, 7]])

In [30]:
x2[1, 2]

3

In [31]:
x2[2, -1]

7

In [32]:
x2[0, 2] = 4

In [42]:
x2

array([[1, 4, 4, 8],
       [3, 2, 3, 6],
       [3, 6, 5, 7]])

In [34]:
x2[:2, :3]

array([[1, 6, 4],
       [3, 2, 3]])

In [36]:
x2[:, 0]

array([1, 3, 3])

In [37]:
x2_sub = x2[:2, :2]

In [39]:
x2_sub[0, 1] = 4

In [40]:
x2_sub

array([[1, 4],
       [3, 2]])

In [41]:
x2

array([[1, 4, 4, 8],
       [3, 2, 3, 6],
       [3, 6, 5, 7]])

In [43]:
x2_sub_copy = x2[:2, :2].copy()

In [44]:
x2_sub_copy

array([[1, 4],
       [3, 2]])

In [45]:
x2_sub_copy[1, 0] = 6

In [46]:
x2_sub_copy

array([[1, 4],
       [6, 2]])

In [47]:
x2

array([[1, 4, 4, 8],
       [3, 2, 3, 6],
       [3, 6, 5, 7]])

In [55]:
grid = np.arange(1, 10).reshape(3, 3)

In [56]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])