In [1]:
import numpy as np
import cv2

In [2]:
#1. Normalize an image using the following steps:
#Loads an image in grayscale mode using OpenCV.
image = cv2.imread('../IMAGEs/flower.jpg', 0)
image.shape

(67, 100)

In [3]:
#Converts the image to floating point representation for calculations.
image_float = image.astype(np.float32)

In [4]:
#Calculates the minimum and maximum pixel values in the image.
min_px = image.min()
max_px = image.max()

min_val = np.min(image_float)
max_val = np.max(image_float)

In [5]:
#Normalizes the image using the formula ((image_float - min_val) / (max_val - min_val))*R.
#if R=256, it will Scale the normalized image to the 0-255 range.
R = 256  # Scale factor
normalized_image = ((image_float - min_px) / (max_px - min_px)) * R

In [6]:
#Displays the original and normalized images using OpenCV.
cv2.imshow('Original Image', image)
cv2.imshow('Normalized Image', normalized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
#2.  Image Encryption: Encrypt the image
#Load the input grayscale image using an image processing library like OpenCV.

image2 = cv2.imread('../IMAGES/CLina.jpg', 0)
image2

array([[159, 156, 163, ..., 167, 146, 125],
       [159, 157, 163, ..., 168, 147, 124],
       [158, 157, 163, ..., 171, 148, 120],
       ...,
       [ 38,  45,  44, ...,  97,  99,  94],
       [ 40,  41,  45, ..., 101, 103, 100],
       [ 45,  34,  56, ..., 101, 104, 103]], dtype=uint8)

In [21]:
#Generate a random key matrix of the same size as the input image. Each element in the key matrix should be a random integer between 0 and 255.
matrix = np.random.randint(0, 256, size=(512, 512), dtype=np.uint8)
matrix

array([[ 44, 104, 170, ...,  73, 171, 111],
       [132,  21,  98, ...,  91, 163, 224],
       [141, 167, 199, ...,  54, 159, 248],
       ...,
       [154, 216, 198, ..., 183,  30,  98],
       [244, 241, 130, ...,  58, 122, 114],
       [159, 148,  21, ..., 201, 217,  62]], dtype=uint8)

In [22]:
#Perform element-wise addition of the input image and the key matrix.
sum_matrix = image2 + matrix
sum_matrix

array([[203,   4,  77, ..., 240,  61, 236],
       [ 35, 178,   5, ...,   3,  54,  92],
       [ 43,  68, 106, ..., 225,  51, 112],
       ...,
       [192,   5, 242, ...,  24, 129, 192],
       [ 28,  26, 175, ..., 159, 225, 214],
       [204, 182,  77, ...,  46,  65, 165]], dtype=uint8)

In [23]:
#Take the modulo 256 of each sum to ensure the result stays within the 0-255 range.
encrypted_image = sum_matrix%256
encrypted_image = encrypted_image.astype(np.uint8)
encrypted_image

array([[203,   4,  77, ..., 240,  61, 236],
       [ 35, 178,   5, ...,   3,  54,  92],
       [ 43,  68, 106, ..., 225,  51, 112],
       ...,
       [192,   5, 242, ...,  24, 129, 192],
       [ 28,  26, 175, ..., 159, 225, 214],
       [204, 182,  77, ...,  46,  65, 165]], dtype=uint8)

In [24]:
#The resulting matrix represents the encrypted image.
cv2.imwrite('../IMAGES/encrypted_image.jpg', encrypted_image)
cv2.imshow("Encrypted Image", encrypted_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
#Decryption: Decrypt the Image
#Perform element-wise subtraction of the encrypted image and the key matrix.
decrypt_matrix = encrypted_image - matrix 
decrypt_matrix

array([[159, 156, 163, ..., 167, 146, 125],
       [159, 157, 163, ..., 168, 147, 124],
       [158, 157, 163, ..., 171, 148, 120],
       ...,
       [ 38,  45,  44, ...,  97,  99,  94],
       [ 40,  41,  45, ..., 101, 103, 100],
       [ 45,  34,  56, ..., 101, 104, 103]], dtype=uint8)

In [29]:
#Take the modulo 256 of each difference to ensure the result stays within the 0-255 range.
decrypted_image = decrypt_matrix % 256
decrypted_image = decrypted_image.astype(np.uint8)
decrypted_image

array([[159, 156, 163, ..., 167, 146, 125],
       [159, 157, 163, ..., 168, 147, 124],
       [158, 157, 163, ..., 171, 148, 120],
       ...,
       [ 38,  45,  44, ...,  97,  99,  94],
       [ 40,  41,  45, ..., 101, 103, 100],
       [ 45,  34,  56, ..., 101, 104, 103]], dtype=uint8)

In [30]:
#The resulting matrix represents the decrypted image.
#Display the original input image, the encrypted image, and the decrypted image for comparison.
cv2.imshow('Original Image', image2)
cv2.imshow('Encrypted Image', encrypted_image)
cv2.imshow('Decrypted Image', decrypted_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Verify that the decrypted image matches the original input image, confirming the correctness of the encryption and decryption process.