In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x>3

array([False, False, False,  True,  True])

In [4]:
x <=3

array([ True,  True,  True, False, False])

In [5]:
(2*x) == (x**2)

array([False,  True, False, False, False])

In [6]:
x

array([1, 2, 3, 4, 5])

In [8]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [9]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])