In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3  = np.random.randint(10, size = (3, 4, 5))

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [7]:
print("dtype: ", x3.dtype)

dtype:  int32


In [8]:
print("itemsize: ", x3.itemsize, " bytes")
print("nbytes: ", x3.nbytes, " bytes")

itemsize:  4  bytes
nbytes:  240  bytes


In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[4]

7

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[1, 2]

8

In [13]:
x2[2, -1]

7

In [14]:
x2[0, 2] = 4

In [15]:
x2

array([[3, 5, 4, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x2[:2, :3]

array([[3, 5, 4],
       [7, 6, 8]])

In [17]:
x2[:, 0]

array([3, 7, 1])

In [18]:
x2_sub = x2[:2, :2]

In [19]:
x2_sub[0, 1] = 4

In [20]:
x2_sub

array([[3, 4],
       [7, 6]])

In [21]:
x2

array([[3, 4, 4, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [22]:
x2_sub_copy = x2[:2, :2].copy()

In [23]:
x2_sub_copy

array([[3, 4],
       [7, 6]])

In [24]:
x2_sub_copy[1, 0] = 6

In [25]:
x2_sub_copy

array([[3, 4],
       [6, 6]])

In [26]:
x2

array([[3, 4, 4, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
grid = np.arange(1, 10).reshape(3, 3)

In [28]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [2, 5])
print(x1, x2, x3)

[1 2] [ 3 99 99] [3 2 1]
