In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a+b

array([5, 6, 7])

In [22]:
M = np.ones((2, 3))
a = np.arange(3)

In [23]:
a

array([0, 1, 2])

In [24]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [30]:
x = np.random.random((10, 3))

In [31]:
x

array([[0.06851148, 0.89128157, 0.17439395],
       [0.28908976, 0.24496348, 0.01665592],
       [0.57610723, 0.69226895, 0.6691445 ],
       [0.81936666, 0.48702133, 0.48504548],
       [0.72918925, 0.40997383, 0.05198049],
       [0.71689186, 0.61589192, 0.81077634],
       [0.25993499, 0.9525164 , 0.04231964],
       [0.08531152, 0.68890391, 0.32069827],
       [0.81219682, 0.22910431, 0.729129  ],
       [0.21199539, 0.79459611, 0.30692666]])

In [39]:
#Xmean = np.mean(x[0])
Xmean = x.mean(0)

In [40]:
Xmean

array([0.4568595 , 0.60065218, 0.36070702])