In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a+b

array([5, 6, 7])

M = np.ones((2, 3))
a = np.arange(3)

a

M+a

In [9]:
b = np.arange(3)[:, np.newaxis]

In [10]:
b

array([[0],
       [1],
       [2]])

In [39]:
#Xmean = np.mean(x[0])
Xmean = x.mean(0)

In [40]:
Xmean

array([0.4568595 , 0.60065218, 0.36070702])

In [12]:
M = np.ones((2, 3))
a = np.arange(3)

In [15]:
M.shape

(2, 3)

In [18]:
a

array([0, 1, 2])