In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 21.2 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 666 ms


In [5]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
data[5:8] = 12, 13, 14
data

array([ 0,  1,  2,  3,  4, 12, 13, 14,  8,  9])

In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr1 = np.arange(1, 7).reshape(2 ,3)
arr2 = np.arange(1, 7).reshape(3, 2)

In [17]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.dot(arr1, arr2)

array([[22, 28],
       [49, 64]])

In [29]:
arr = np.random.randint(1, 12, size=(3, 4, 2))
arr

array([[[11,  2],
        [11, 10],
        [ 2,  9],
        [ 9,  6]],

       [[ 4,  6],
        [ 1, 10],
        [ 4,  2],
        [ 4,  9]],

       [[ 4,  9],
        [ 4,  9],
        [ 3,  7],
        [10,  7]]])

In [36]:
points = np.arange(1, 11, 2)
points

array([1, 3, 5, 7, 9])

In [38]:
xs, ys = np.meshgrid(points, points)
xs

array([[1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9]])

In [40]:
arr = np.random.randn(4, 4)
arr

array([[-0.53134065,  0.22041755, -0.16019735, -1.36167482],
       [-0.3044745 , -1.70955328,  2.5908458 ,  1.3178277 ],
       [-0.41823605, -1.78278076, -0.33815809,  2.07745503],
       [ 0.38732666,  0.3877634 ,  1.29474413, -1.16179661]])

In [42]:
cond = arr > 0
cond

array([[False,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [46]:
array = np.where(arr>0, 2, -2)
array

array([[-2,  2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2,  2],
       [ 2,  2,  2, -2]])

In [54]:
array.mean(axis=1)

array([-1.,  0., -1.,  1.])