In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 26.5 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 948 ms


In [5]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
data[5:8] = 12, 13, 14
data

array([ 0,  1,  2,  3,  4, 12, 13, 14,  8,  9])

In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr1 = np.arange(1, 7).reshape(2 ,3)
arr2 = np.arange(1, 7).reshape(3, 2)

In [9]:
arr.T

NameError: name 'arr' is not defined

In [ ]:
np.dot(arr1, arr2)

In [10]:
arr = np.random.randint(1, 12, size=(3, 4, 2))
arr

array([[[ 2,  5],
        [ 4,  4],
        [ 7,  2],
        [ 9, 11]],

       [[ 4,  7],
        [ 1,  4],
        [ 7,  1],
        [ 7,  4]],

       [[ 6,  7],
        [10,  9],
        [ 8,  9],
        [ 8,  8]]])

In [11]:
points = np.arange(1, 11, 2)
points

array([1, 3, 5, 7, 9])

In [12]:
xs, ys = np.meshgrid(points, points)
xs

array([[1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9]])

In [13]:
arr = np.random.randn(4, 4)
arr

array([[ 0.92750683,  0.7063317 ,  1.16334399, -0.49603709],
       [-1.4161515 , -1.20032765, -0.51540019,  0.00575798],
       [ 1.31539942, -0.0192029 ,  0.39902154,  0.54726383],
       [ 2.13760252,  0.41186602, -0.79287738, -0.01080061]])

In [14]:
cond = arr > 0
cond

array([[ True,  True,  True, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [ True,  True, False, False]])

In [15]:
array = np.where(arr>0, 2, arr)
array

array([[ 2.        ,  2.        ,  2.        , -0.49603709],
       [-1.4161515 , -1.20032765, -0.51540019,  2.        ],
       [ 2.        , -0.0192029 ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -0.79287738, -0.01080061]])

In [16]:
array.mean(axis=1)

array([ 1.37599073, -0.28296983,  1.49519928,  0.7990805 ])

In [34]:
arr = np.random.randint(1 ,10, size=(4, 3))
arr

array([[1, 1, 9],
       [4, 8, 2],
       [8, 8, 2],
       [3, 7, 5]])

In [35]:
arr.sort(0)
arr

array([[1, 1, 2],
       [3, 7, 2],
       [4, 8, 5],
       [8, 8, 9]])