In [8]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        

In [9]:
values = np.random.randint(1, 10, size=6)
values

array([6, 1, 4, 4, 8, 4])

In [10]:
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ,
       0.25      ])

In [11]:
big_array = np.random.randint(1, 100, size = 1000000)

In [15]:
%timeit compute_reciprocals(big_array)

1.74 s ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
%timeit (1.0 / big_array)

2.74 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [24]:
x = np.arange(1, 6)
np.multiply.reduce(x)

120